/* Pure screen-space label placement for the Prism wall. */
(function(global,factory){
 'use strict';
 const api=factory();
 if(typeof module==='object'&&module.exports)module.exports=api;
 if(global)global.PrismLabels=api;
})(typeof window!=='undefined'?window:globalThis,function(){
 'use strict';
 const R=25,CRYSTAL_HALF=12.48,SELECTION_HALF=19,SELECTION_END=3,PENDING_HALF=21,PENDING_END=5,CLEARANCE=2,MIN_FONT=11,MIN_ENVELOPE=24,MAX_SEARCH=50000;
 const midpoint=(a,b,t=.5)=>({x:a.x+(b.x-a.x)*t,y:a.y+(b.y-a.y)*t});
 const rectAt=(point,line)=>({left:point.x-line.width/2,right:point.x+line.width/2,top:point.y-line.height/2,bottom:point.y+line.height/2});
 const corners=rect=>[{x:rect.left,y:rect.top},{x:rect.right,y:rect.top},{x:rect.right,y:rect.bottom},{x:rect.left,y:rect.bottom}];
 function canvasRect(canvas){const left=canvas.left||0,top=canvas.top||0;if(!(canvas.width>0&&canvas.height>0))throw Error('Canvas width and height must be positive.');return {left,top,right:left+canvas.width,bottom:top+canvas.height,width:canvas.width,height:canvas.height}}
 function segment(start,end,half,extension=0){const dx=end.x-start.x,dy=end.y-start.y,length=Math.hypot(dx,dy);if(!length)throw Error('A screen Line needs distinct tube endpoints.');const tx=dx/length,ty=dy/length,nx=-ty,ny=tx,a={x:start.x-tx*extension,y:start.y-ty*extension},b={x:end.x+tx*extension,y:end.y+ty*extension};return [{x:a.x+nx*half,y:a.y+ny*half},{x:b.x+nx*half,y:b.y+ny*half},{x:b.x-nx*half,y:b.y-ny*half},{x:a.x-nx*half,y:a.y-ny*half}]}
 function projection(points,axis){const values=points.map(point=>point.x*axis.x+point.y*axis.y);return [Math.min(...values),Math.max(...values)]}
 function intersects(first,second){for(const shape of [first,second])for(let index=0;index<shape.length;index++){const next=shape[(index+1)%shape.length],edge={x:next.x-shape[index].x,y:next.y-shape[index].y},length=Math.hypot(edge.x,edge.y),axis={x:-edge.y/length,y:edge.x/length},a=projection(first,axis),b=projection(second,axis);if(a[1]<b[0]||b[1]<a[0])return false}return true}
 const overlaps=(a,b)=>a.left<b.right+CLEARANCE&&b.left<a.right+CLEARANCE&&a.top<b.bottom+CLEARANCE&&b.top<a.bottom+CLEARANCE;
 function hitsCircle(rect,circle){const x=Math.max(rect.left,Math.min(circle.x,rect.right)),y=Math.max(rect.top,Math.min(circle.y,rect.bottom));return Math.hypot(x-circle.x,y-circle.y)<=circle.radius}
 const inside=(rect,canvas)=>rect.left>=canvas.left+CLEARANCE&&rect.right<=canvas.right-CLEARANCE&&rect.top>=canvas.top+CLEARANCE&&rect.bottom<=canvas.bottom-CLEARANCE;
 function prepare(input){if(!input||!(input.scale>0)||!Array.isArray(input.nodes)||!input.nodes.length||!Array.isArray(input.lines))throw Error('Provide screen geometry, canvas, and a positive scale.');const canvas=canvasRect(input.canvas),connectorIds=new Set(),nodes=input.nodes.map(node=>{if(!node||typeof node.id!=='string'||connectorIds.has(node.id)||!Number.isFinite(node.x)||!Number.isFinite(node.y))throw Error('Invalid screen connector.');connectorIds.add(node.id);return {...node}}),lineIds=new Set(),numbers=new Set(),lines=input.lines.map(line=>{const number=String(line?.number??'');if(!line||typeof line.id!=='string'||lineIds.has(line.id)||!number||numbers.has(number)||!line.start||!line.end||![line.start.x,line.start.y,line.end.x,line.end.y].every(Number.isFinite)||Number(line.fontSizePx)<MIN_FONT)throw Error('Invalid screen Line.');lineIds.add(line.id);numbers.add(number);return {...line,start:{...line.start},end:{...line.end},width:Math.max(MIN_ENVELOPE,Number(line.width)||0),height:Math.max(MIN_ENVELOPE,Number(line.height)||0)}});return {canvas,nodes,lines,scale:input.scale}}
 function obstacleSet(geometry){const scale=geometry.scale,polygons=geometry.lines.flatMap(line=>[
  {kind:'crystal',lineId:line.id,points:segment(line.start,line.end,CRYSTAL_HALF*scale)},
  {kind:'selection',lineId:line.id,points:segment(line.start,line.end,SELECTION_HALF*scale,SELECTION_END*scale)},
  {kind:'pending',lineId:line.id,points:segment(line.start,line.end,PENDING_HALF*scale,PENDING_END*scale)}]);
  return {polygons,blocking:geometry.lines.map(line=>({points:segment(line.start,line.end,PENDING_HALF*scale+CLEARANCE,PENDING_END*scale+CLEARANCE)})),circles:geometry.nodes.map(node=>({...node,radius:(R+.36)*scale+CLEARANCE}))}}
 function candidates(line,geometry,center){const dx=line.end.x-line.start.x,dy=line.end.y-line.start.y,length=Math.hypot(dx,dy);if(!length)return [];const tangent={x:dx/length,y:dy/length},normal={x:-tangent.y,y:tangent.x},middle=midpoint(line.start,line.end),outward=normal.x*(middle.x-center.x)+normal.y*(middle.y-center.y)>=0?1:-1,sides=[outward,-outward],support=Math.abs(normal.x)*line.width/2+Math.abs(normal.y)*line.height/2,base=PENDING_HALF*geometry.scale+support+CLEARANCE,result=[],seen=new Set(),add=(x,y,strategy)=>{const key=x.toFixed(2)+','+y.toFixed(2);if(!seen.has(key)){seen.add(key);result.push({x,y,strategy,rank:result.length})}};
  for(const t of [.5,.38,.62,.25,.75])for(const side of sides)for(const extra of [0,6,12,20,30,42]){const anchor=midpoint(line.start,line.end,t),offset=base+extra;add(anchor.x+normal.x*side*offset,anchor.y+normal.y*side*offset,extra?'normal-offset':'adjacent-normal')}
  for(const side of sides)for(const shift of [12,-12,24,-24,40,-40])add(middle.x+normal.x*side*base+tangent.x*shift,middle.y+normal.y*side*base+tangent.y*shift,'normal-tangent');
  const angle0=Math.atan2(normal.y*outward,normal.x*outward),steps=[0];for(let step=1;step<=12;step++)steps.push(step,-step);for(let extra=0;extra<=96;extra+=8)for(const step of steps){const angle=angle0+step*Math.PI/12,radius=base+extra;add(middle.x+Math.cos(angle)*radius,middle.y+Math.sin(angle)*radius,'bounded-radial')}return result}
 function place(input,options={}){const geometry=prepare(input),obstacles=obstacleSet(geometry),center={x:geometry.nodes.reduce((sum,node)=>sum+node.x,0)/geometry.nodes.length,y:geometry.nodes.reduce((sum,node)=>sum+node.y,0)/geometry.nodes.length},metrics={searchNodes:0,staticCandidateChecks:0,compatibilityCandidateChecks:0,labelComparisons:0,searchNodeLimit:options.maxSearchNodes||MAX_SEARCH};
  const valid=(point,line)=>{metrics.staticCandidateChecks++;const rect=rectAt(point,line),shape=corners(rect);return inside(rect,geometry.canvas)&&!obstacles.blocking.some(item=>intersects(shape,item.points))&&!obstacles.circles.some(circle=>hitsCircle(rect,circle))};
  const labels=geometry.lines.map(line=>({line,candidates:candidates(line,geometry,center).filter(point=>valid(point,line))})),order=[...labels].sort((a,b)=>a.candidates.length-b.candidates.length||String(a.line.number).localeCompare(String(b.line.number)));metrics.maxCandidatesPerLine=Math.max(0,...labels.map(label=>label.candidates.length));const placed=new Map();let best=new Map(),limited=false;
  const compatible=(point,line)=>{metrics.compatibilityCandidateChecks++;const rect=rectAt(point,line);for(const other of placed.values()){metrics.labelComparisons++;if(overlaps(rect,other.bounds))return false}return true};
  function solve(){metrics.searchNodes++;if(placed.size>best.size)best=new Map(placed);if(metrics.searchNodes>metrics.searchNodeLimit){limited=true;return false}if(placed.size===labels.length)return true;const choice=order.find(label=>!placed.has(label.line.id));for(const point of choice.candidates){if(!compatible(point,choice.line))continue;placed.set(choice.line.id,{id:choice.line.id,number:choice.line.number,x:point.x,y:point.y,width:choice.line.width,height:choice.line.height,fontSizePx:choice.line.fontSizePx,bounds:rectAt(point,choice.line),strategy:point.strategy,rank:point.rank});if(solve())return true;placed.delete(choice.line.id);if(limited)return false}return false}
  const staticReady=labels.every(label=>label.candidates.length),ok=staticReady&&solve(),selected=ok?placed:best,placements=geometry.lines.map(line=>selected.get(line.id)).filter(Boolean),unsolved=geometry.lines.filter(line=>!selected.has(line.id)).map(line=>({id:line.id,number:line.number,staticCandidates:labels.find(label=>label.line.id===line.id).candidates.length}));return {ok,placements,unsolved,failureReason:ok?null:!staticReady?'static-exhaustion':limited?'search-limit':'no-complete-layout',metrics,geometry,obstacles}}
 function validate(result){const errors=[];for(const label of result.placements){const shape=corners(label.bounds);if(label.fontSizePx<MIN_FONT)errors.push(label.id+': text below 11px');if(!inside(label.bounds,result.geometry.canvas))errors.push(label.id+': outside canvas');for(const obstacle of result.obstacles.polygons)if(intersects(shape,obstacle.points))errors.push(label.id+': intersects '+obstacle.kind+' '+obstacle.lineId);for(const circle of result.obstacles.circles)if(hitsCircle(label.bounds,circle))errors.push(label.id+': intersects connector '+circle.id)}for(let a=0;a<result.placements.length;a++)for(let b=a+1;b<result.placements.length;b++)if(overlaps(result.placements[a].bounds,result.placements[b].bounds))errors.push(result.placements[a].id+'/'+result.placements[b].id+': overlap');return errors}
 return {placeLabels:place,validatePlacement:validate,constants:{connectorRadius:R,crystalHalfHeight:CRYSTAL_HALF,selectionHalfHeight:SELECTION_HALF,pendingHalfHeight:PENDING_HALF,minFontPx:MIN_FONT,minEnvelopePx:MIN_ENVELOPE,maxSearchNodes:MAX_SEARCH}};
});
